image: node:lts

cache:
  paths:
    - node_modules/

pages:
  before_script:
    # Clean public folder
    - find public -mindepth 1 -maxdepth 1 -type d | xargs rm -rf
    - find public -type f -name "*.html" | xargs rm -rf
    # Install packages
    - npm install
  script:
    # Build application and move content to public folder
    - npm run publish
    - rm -rf public/*
    - mv out/* public
  after_script:
    # Cleanup
    - rm -rf out
  artifacts:
    paths:
      - public
  only:
    - master

pages_develop:
  extends: pages
  script:
    # Build application and move content to a separate directory within public folder
    - npm run publish
    - rm -rf public/develop
    - mv out/* public/develop
  artifacts:
    paths:
      - public/develop
  only:
    - develop
