image: node:lts

pages:
  before_script:
    # Clean public folder
    - find public -mindepth 1 -maxdepth 1 -type d | xargs rm -rf
    - find public -type f -name "*.html" | xargs rm -rf
    # Install packages
    - npm install
  script:
    # Build application and move content to public folder
    - npm run publish
    - rm -rf public/*
    - mv out/* public
  after_script:
    # Cleanup
    - rm -rf out
  artifacts:
    paths:
      - public
  only:
    - master

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g firebase-tools

deploy:
  stage: deploy
  before_script:
    # Clean public folder
    - find public -mindepth 1 -maxdepth 1 -type d | xargs rm -rf
    - find public -type f -name "*.html" | xargs rm -rf
    # Install packages and Firebase CLI
    - npm install
    - npm install -g firebase-tools
  script:
    # Build application and move content to public folder
    - npm run publish
    - rm -rf public/*
    - mv out/* public
    - firebase deploy --only hosting --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
  only:
    #- develop
    - patch__safari-flip-issue


variables:
  FIREBASE_API_KEY: "AIzaSyC1rKFG85X9A1Q_0n_3aKZoy8MkfHdEBHw"
  FIREBASE_AUTH_DOMAIN: "chat-bot-1a3ba.firebaseapp.com"
  FIREBASE_PROJECT_ID: "chat-bot-1a3ba"
  FIREBASE_STORAGE_BUCKET: "chat-bot-1a3ba.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID: "943974249469"
  FIREBASE_APP_ID: "1:943974249469:web:43eca5e731d81f3c781f94"
  FIREBASE_MEASUREMENT_ID: "G-CVN8539YHK"
  FIREBASE_TOKEN: "1//0gN-VPnFCA6GeCgYIARAAGBASNwF-L9Ir6yGDzzoqmuL71rnB7jbFO5ldJn-vPoXmr9_RSBDS8DhOvdSU9yB76FfMrRTx846eUD8"

