image: node:lts

cache:
  paths:
    - node_modules/

pages:
  before_script:
    # Clean public folder
    - find public -mindepth 1 -maxdepth 1 -type d | xargs rm -rf
    - find public -type f -name "*.html" | xargs rm -rf
    # Install packages
    - npm install
  script:
    # Build application and move content to public folder
    - npm run publish
    - rm -rf public/*
    - mv out/* public
  after_script:
    # Cleanup
    - rm -rf out
  artifacts:
    paths:
      - public
  only:
    - master

deploy_firebase:
  stage: deploy
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build  # Modify this command based on your build process
    - firebase use --clear
    - firebase use --add $FIREBASE_PROJECT_ID --token "$FIREBASE_TOKEN"
    - firebase deploy --only hosting --token "$FIREBASE_TOKEN"
  only:
    - develop
